### ISSUE TITLE
Inconsistent use of underscores for protected functions in Python

### ISSUE THREAD

**Issue by domire8** [epfl-lasa/modulo#125]
We have small inconsistencies for the single and double underscore pattern for protected and private functions in Python. For example,  the `_validate_parameter` function in `ComponentInterface` has an underscore to indicate its protected but the `on_XXX_callback` functions in `LifecylceComponent` don't have that.

I'd prefer to remove the single underscores and only mark private functions with double underscore. This is quite a breaking change for the dynamic components but I would take care of it. Any objections @eeberhard @buschbapti ?

**Comment by domire8** [comment]
Ok I guess I'm starting to contradict myself here.

For other functions, such as `_step`, etc. that are defined in the component interface but overridden in the `Component` and `LifecycleComponent` (and hence cannot have double underscore), I'd like to keep the underscore. Maybe in other words:

I'd like to have to following pattern:
- All public functions and functions that should be overridden by a derived component, we use NO underscore.
- All protected functions that are defined in the component interface and required in the `Component` and `LifecycleComponent` we use SINGLE underscore to indicate to the user that those should not be used nor overridden.
- As much as it's possible, we use DOUBLE underscore for all other functions

**Comment by buschbapti** [comment]
Right `step()` is not actually redefined by the final component only the `on_step()`. Then I agree there. Basically, anything publicly usable, even if protected in cpp should be without underscores. To be fair, they could be made public in cpp for consistency but probably that is not necessary.

**Comment by domire8** [comment]
Resolved in #126 and #127
